config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  resources :items
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item criado com sucesso." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item excluido com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:description, :category, :status, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "Usuário cadastrado com sucesso." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "Editado com sucesso!!"}
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "Usuario excluido com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
  <h1 style="font-size:40px">Seja bem vindo á sua pagina de estudos! </h1>
<hr>
 <div class="hero">
 <div class="hero-text">
<hr>
  <H3 style="font-size:25px"> O sucesso nos estudos começa com um bom ambiente! </h3>
<hr>
  <br>
  <p style="font-size:20px">Ambiente para você estudante conseguir se organizar na hora de estudar para seus exames. Aqui você pode criar um usuario e cadastrar seus itens de estudos, facilitando assim a rotina de estudos.Após a conclusão de estudo o item pode ser deletado... <p> 
<hr>
 </div>
  </div>
  <hr>
 <%=  link_to 'Cadastrar Usuários', users_path %>
  <%= link_to 'Cadastrar Itens', items_path %>
  <H3 style="font-size:30px"> Aproveite! </h3>
          

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= collection_select(:item, :user_id, User.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  

<% end %>

app/views/items/edit.html.erb
<h1>Editar Itens</h1>
<hr>

<%= render 'form', item: @item %>

<%= link_to 'Novo', @item %> |
<%= link_to 'Voltar', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Itens cadastrados</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Categoria</th>
      <th>Status</th>
      <th colspan="4"></th>
    </tr>
  </thead>
<hr>
  <tbody>
    <% @items.each do |item| %> 
      <tr>
        <td><%= item.user.name%></td>
        <td><%= item.description%></td>
        <td><%= item.category %></td>
        <td><%= item.status %></td> 
        <th><%= link_to 'Editar', edit_item_path(item) %></th>
        <th><%= link_to 'Deletar', item, method: :delete, data: { confirm: 'Você deseja deletar?' } %></th>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<hr>

<%= link_to 'Criar novo item', new_item_path %>
<%= link_to 'Home', 'http://localhost:3000' %>

app/views/items/new.html.erb
<h1>Cadastro de item</h1>
<hr>

<%= render 'form', item: @item %>

<%= link_to 'Voltar', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descrição:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>

<%= link_to 'Editar', edit_item_path(@item) %> |
<%= link_to 'Sair', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>Guia de estudos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>


  <body>
   
    <%=yield %>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editar Usuário</h1>
<hr>

<%= render 'form', user: @user %>

<%= link_to 'Exibir', @user %> |
<%= link_to 'Voltar', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuários</h1>
<hr>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data do exame</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.date %></td>
        <th><%= link_to 'Detalhes', user %></th>
        <th><%= link_to 'Editar', edit_user_path(user) %></th>
        <th><%= link_to 'Deletar', user, method: :delete, data: { confirm: 'Tem certeza' } %></th>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<hr>
<%= link_to 'Novo cadastro', new_user_path %>
<%= link_to 'Home', 'http://localhost:3000' %>

app/views/users/new.html.erb
<h1>Novo usuário</h1>
<hr>

<%= render 'form', user: @user %>

<%= link_to 'Voltar', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Data do exame:</strong>
  <%= @user.date %>
</p>

<%= link_to 'Exibir', edit_user_path(@user) %> |
<%= link_to 'voltar', users_path %>